const { version } = require('../../package.json');

export const header = `// Code generated by konstellio (@konstellio/cli@${version}). DO NOT EDIT.
// Please don't change this file manually but run \`konstellio generate\` to update it.
// For more information, please read the docs: https://konstell.io/docs/cli/

`;
