// Code generated by konstellio (@konstellio/cli@0.2.9). DO NOT EDIT.
// Please don't change this file manually but run `konstellio generate` to update it.
// For more information, please read the docs: https://konstell.io/docs/cli/

export type ID = any;
export type DateTime = Date;

export interface UserGroup {
	id: ID;
	name: string;
	roles: string[];
}

export interface UserGroupIndexes {
	id: ID;
}

export interface User {
	id: ID;
	username: string;
	password: string;
	groups: ID[];
}

export interface UserIndexes {
	id: ID;
	username: string;
}